inherits:
  - duplicated
  - utils:base
  - utils:no-design-checks
  - utils:fix
  - .prospector-tests.yaml

mypy:
  options:
    python-version: "3.10"

ruff:
  options:
    target-version: py310
  disable:
    - D103 # Missing docstring in public function
    - D107 # Missing docstring in `__init__`
    - TD # TODO
    - FIX # FIXME
    - A001 # Variable `{}` is shadowing a Python builtin
    - A002 # Function argument `{}` is shadowing a Python builtin
    - PLW2901 # Outer `{}` statement variable `{}` overwritten by inner `{}` statement target
