inherits:
  - duplicated
  - utils:base
  - utils:no-design-checks
  - utils:unsafe

mypy:
  options:
    python_version: "3.9"

ruff:
  disable:
    - D103 # Missing docstring in public function
    - D107 # Missing docstring in `__init__`
