dist: bionic
language: python

python:
  - "2.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"

before_install:
  - sudo apt-get -y install python3-venv

script:
  - make check
  - .build/venv/bin/nosetests -v --cover-package papyrus
