language: python

python: 3.11

env:
  - TOX_ENV=py27
  - TOX_ENV=py38
  - TOX_ENV=py39
  - TOX_ENV=py310
  - TOX_ENV=py311

matrix:
  include:
  - python: 3.11
    env:
    - TOX_ENV=py311

install:
  - sudo rm -rf /usr/lib/python2.7/dist-packages/six*
  - pip install flake8 tox

script:
  - flake8 papyrus
  - tox -e $TOX_ENV --sitepackages -- -v --cover-package papyrus
